"""step5_iot_sensors

Revision ID: 4da17eed23f2
Revises: 0003_step4_product_shipment
Create Date: 2026-09-18 22:04:30.767370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4da17eed23f2'
down_revision = '0003_step4_product_shipment'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_code', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='sensorstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=False)
    op.create_index(op.f('ix_sensors_sensor_code'), 'sensors', ['sensor_code'], unique=True)
    op.create_index(op.f('ix_sensors_shipment_id'), 'sensors', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_sensors_status'), 'sensors', ['status'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_sensor_id'), 'sensor_readings', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_shipment_id'), 'sensor_readings', ['shipment_id'], unique=False)
    op.alter_column('batches', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('IN_PRODUCTION', 'READY_FOR_SHIPMENT', 'IN_TRANSIT', 'DELIVERED', 'EXPIRED', 'CANCELLED', name='batchstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('custody_transfers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_custody_transfers_from_organization_id'), 'custody_transfers', ['from_organization_id'], unique=False)
    op.create_index(op.f('ix_custody_transfers_to_organization_id'), 'custody_transfers', ['to_organization_id'], unique=False)
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('shipment_events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CREATED', 'DISPATCHED', 'RECEIVED', 'DELAYED', 'HAZARD', 'CUSTODY_TRANSFER', name='shipmenteventtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('shipment_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PLANNED', 'DISPATCHED', 'IN_TRANSIT', 'DELIVERED', 'FAILED', name='shipmentstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'MANUFACTURER', 'LOGISTICS', 'WAREHOUSE', 'HOSPITAL', 'AUDITOR', name='userrole', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANUFACTURER', 'LOGISTICS', 'WAREHOUSE', 'HOSPITAL', 'AUDITOR', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('shipments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('shipments', 'status',
               existing_type=sa.Enum('PLANNED', 'DISPATCHED', 'IN_TRANSIT', 'DELIVERED', 'FAILED', name='shipmentstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('shipment_events', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('shipment_events', 'event_type',
               existing_type=sa.Enum('CREATED', 'DISPATCHED', 'RECEIVED', 'DELAYED', 'HAZARD', 'CUSTODY_TRANSFER', name='shipmenteventtype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('organizations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('organizations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_custody_transfers_to_organization_id'), table_name='custody_transfers')
    op.drop_index(op.f('ix_custody_transfers_from_organization_id'), table_name='custody_transfers')
    op.alter_column('custody_transfers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('batches', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('batches', 'status',
               existing_type=sa.Enum('IN_PRODUCTION', 'READY_FOR_SHIPMENT', 'IN_TRANSIT', 'DELIVERED', 'EXPIRED', 'CANCELLED', name='batchstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_sensor_readings_shipment_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_sensor_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_sensors_status'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_shipment_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_sensor_code'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_table('sensors')
    # ### end Alembic commands ###
